### ISSUE TITLE
UI only opens once on Ubuntu 18.04

### ISSUE THREAD

**Issue by iGadget** [flathub/com.nextcloud.desktopclient.nextcloud#10]
When installing the flatpak version of the Nextcloud Client on vanilla Ubuntu 18.04, the user interface of the app opens only once. As soon as it's configured, it does not open anymore, nor does it show an icon in the top bar.
The version from the PPA works flawlessly.

**Comment by tilosp** [comment]
Solved by https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/commit/518e7c06718f211966a6231a87e57090968e911d
