### ISSUE TITLE
The app hasn't been updated to 3.10.1

### ISSUE THREAD

**Issue by BigmenPixel0** [flathub/com.nextcloud.desktopclient.nextcloud#128]
You need to restart the building (it seems be an onetime error?)

**Comment by koelle25** [comment]
@tilosp @juliushaertl 

Flathub (https://flathub.org/apps/com.nextcloud.desktopclient.nextcloud) does not yet have 3.10.1. It seems there was a temporary failure in the build process:
 ```
builddir/files/share/appdata/com.nextcloud.desktopclient.nextcloud.appdata.xml: FAILED:
• url-not-found         : <screenshot> url not valid [https://nextcloud.com/wp-content/uploads/2022/04/linux.png]: Failed to connect to nextcloud.com port 443 after 5001 ms: Timeout was reached
```

Can you re-trigger the build process please? https://buildbot.flathub.org/#/builders/6/builds/76849

**Comment by tilosp** [comment]
done
