### ISSUE TITLE
 [Bug]: Desktop client not starting

### ISSUE THREAD

**Issue by geez0x1** [flathub/com.nextcloud.desktopclient.nextcloud#169]
Since the past two days I cannot get the client to start on my desktop machine (Ubuntu 24.04).

From CLI I see this:
```
geez@geez-desktop:~$ flatpak run com.nextcloud.desktopclient.nextcloud 
QSocketNotifier: Can only be used with threads started with QThread
nextcloud.gui.application: Migrating old config from "/home/geez/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/geez/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/geez/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/geez/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("nextCloud_a_sync.log", "nextCloud_b_sync.log", "nextCloud_b_sync.log.1", "nextCloud_sync.log")
nextcloud.gui.application: Fallback move of  "nextCloud_a_sync.log" also failed
nextcloud.gui.application: Fallback move of  "nextCloud_b_sync.log" also failed
nextcloud.gui.application: Fallback move of  "nextCloud_b_sync.log.1" also failed
nextcloud.gui.application: Fallback move of  "nextCloud_sync.log" also failed
```
as well as the following popup:
![Screenshot from 2024-07-13 16-40-10](https://github.com/user-attachments/assets/17778701-8342-4ade-bf4c-4e940587a013)

Clicking quit generates the following message in CLI before the application exits:
```
[2:47:0713/164012.135782:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Address already in use (98)
```
Furthermore this is suspicious, which was shown when I performed a `sudo flatpak update --commit=fd6f202522559c91562b8fdf3aaa02cc473cebf29be04d51f1e6aec97cf4def2 com.nextcloud.desktopclient.nextcloud` to try a different version of the flatpak.
```
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /root/.local/share
- /usr/local/share/
- /usr/share/
```
However, this might just be related to the `sudo` part of that (needed to install a specific commit). In fact my user's environment variables do contain that directory.

I've tried a lot of things, including:
- Reinstall the flatpak and use different versions
- Remove the flatpak's directory from `~/.var/app/`. This gives me the "initial setup" for the app, which then also starts to fail as soon as it starts to try to write config files.
- Make the directory in question `chmod 777`
- Reinstall flatpak itself
- Add the environment variables above to the flatpak overrides for this flatpak
- Downgrade a recent apparmor update and boot the old kernel

Notably, I don't think I changed anything. I regularly update the machine, but comparing to my laptop (Ubuntu 24.04 and no issues), the only difference appears to be a kernel upgrade and that apparmor update I mentioned. Finally, I did notice that Steam started having issues at the same time (steamwebhelper hanging), as well as kdenlive (complaining "cannot start KIO worker"). However, all my other flatpak applications seem to work (which are quite a few). My nextcloud is critical - hopefully by resolving this one I can also understand how to fix the others.

This seems similar to #140. Any ideas?

**Comment by Ra72xx** [comment]
I got it working again by:
```
sudo systemctl stop apparmor
sudo aa-teardown
sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0 && sysctl - w kernel.apparmor_restrict_unprivileged_userns=0
```
**and** adding the path 
`~/.var/app/com/com.nextcloud.desktopclient.nextcloud/`
to the allowed paths with FlatSeal.

Disabling AppArmor and/or the unprivileged user namespace option since Ubuntu 24.04 seems to be a good solution for Flatpak problems. Because of errors like this you can clearly see that Flatpak is not the supported package format on Ubuntu, they want to push Snap :-(.

However, this is neither elegant nor secure.

**Comment by Ra72xx** [comment]
I also found this page: [https://github.com/flatpak/flatpak/wiki/User-namespace-requirements](url), which, however, somehow contradicts the way I deal with Flatpak problems on Ubuntu....

**Comment by ekasprzak** [comment]
It's actually a fresh bug with AppArmor in Ubuntu which should be fixed (hopefully) soon.
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811

Proposed worakround there (without disabling whole AppArmor):

```bash
sudo aa-disable /usr/bin/bwrap
```
