### ISSUE TITLE
New UI won't synchronise automatically

### ISSUE THREAD

**Issue by jbpichancourt** [flathub/com.nextcloud.desktopclient.nextcloud#19]
Thanks for your hardwork! But ....This new flatpak version of the nextcloud client (3.0.1. ) won't autostart or synchronise on the background. I need to click on the launcher several time to expect accessing the new UI and finally synch my files. Then from the new UI we can access the old UI by clicking on settings, which is more useful. But if I close the new UI, it shuts down synchronisation. Currently this new version is not functional. 
Thx in advance for fixing these issues (i'm on arch linux)

**Comment by monreal** [comment]
There's a new release 3.0.3 out, maybe it would fix this and other problems the published release has right now.

**Comment by tilosp** [comment]
@jbpichancourt is this still happening on the latest version (`3.1.2`)

**Comment by bkhl** [comment]
It sounds like the issue here was the same as in https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/20, which as I mention there has been resolved in `3.1.2`.

**Comment by tilosp** [comment]
> It sounds like the issue here was the same as in #20, which as I mention there has been resolved in `3.1.2`, provided the user creates an autostart file like the one in my last comment there.

I think you are right, closing this now.


@jbpichancourt feel free to reopen if the issue still persists
