### ISSUE TITLE
Please update to v3.1.2

### ISSUE THREAD

**Issue by aquilacooper** [flathub/com.nextcloud.desktopclient.nextcloud#28]
The Flathub repository for the Nextcloud Desktop Client is still offering version 3.0.2 as the latest available version. Version 3.1.1 was [released on 2020-12-23](https://github.com/nextcloud/desktop/releases/tag/v3.1.1).

Please therefore update the Flathub repository to v3.1.1.

Thank you!

**Comment by aquilacooper** [comment]
[Version 3.1.2](https://github.com/nextcloud/desktop/releases/tag/v3.1.2) was released nine hours ago, at 2021-01-28T17:30Z.

**Comment by tilosp** [comment]
Resolved by https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/32
