### ISSUE TITLE
nextcloud quits automatically after a while when there is no window visible

### ISSUE THREAD

**Issue by gkiagia** [flathub/com.nextcloud.desktopclient.nextcloud#3]
I am running the latest nexcloud flatpak on a gnome-wayland 3.36 desktop.
I am using the workaround mentioned in flathub/org.nextcloud.Nextcloud#56  (`flatpak override --user --own-name=org.kde.* org.nextcloud.Nextcloud`) to make the tray icon work... and it works.

However, when nextcloud is minimized in the tray, it quits after about a minute or so... If I keep its window visible, then it keeps running. There is no apparent crash, it just seems to do some sort of timeout exit.

**Comment by tilosp** [comment]
@gkiagia have you allowed nextcloud to run in the background?

you can check this in gnome settings under Applications.

**Comment by gkiagia** [comment]
I can no longer reproduce this after upgrading from `org.nextcloud.Nextcloud` to `com.nextcloud.desktopclient.nextcloud` ...
I did not know about this setting, so I had never touched it. If it was not allowed to run in the background by default, then maybe this was the reason.
