### ISSUE TITLE
creates autostart desktop file in wrong location with wrong content

### ISSUE THREAD

**Issue by vasyugan** [flathub/com.nextcloud.desktopclient.nextcloud#4]
when you enable autostart in the settings, a desktop file is created in ~/.var/app/org.nextcloud.Nextcloud/config/autostart
and the exec line is
Exec=/app/bin/nextcloud

Instead, it must be created in ~/.config/autostart and the exec line must be
Exec=flatpak run org.nextcloud.Nextcloud

**Comment by tilosp** [comment]
Moved to https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/18
