### ISSUE TITLE
No tray icon, again, "[unknown 	failed to register service "org.kde.StatusNotifierItem-3-1""

### ISSUE THREAD

**Issue by vasyugan** [flathub/com.nextcloud.desktopclient.nextcloud#5]
As in bug flathub/org.nextcloud.Nextcloud#9 I don't see a tray icon, however running the nextcloud client as 

flatpak run --talk-name=org.kde.StatusNotifierWatcher org.nextcloud.Nextcloud 

doesn't make a difference. Tested on Debian Buster with MATE and GNOME, on both of which statusnotifier support is present (and works fine with the Nextcloud AppImage). In the debug log I find the line: 
`[unknown 	failed to register service "org.kde.StatusNotifierItem-3-1"`

**Comment by tilosp** [comment]
Solved by https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/commit/518e7c06718f211966a6231a87e57090968e911d
