### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by ramcq** [flathub/com.nextcloud.desktopclient.nextcloud#7]
I have NextCloud 2.6.0 flatpak installed, but inside the app it says I have version 2.5.3git. I'm not sure how this happened because clearly the manifest is pointing to the v2.6.0 tag, but it means I am receiving pop-up notifications telling me to upgrade to 2.6.0.

**Comment by tilosp** [comment]
Seems to work now. Feel free to reopen if it's still a problem.
