### ISSUE TITLE
Launch on System Startup does not work

### ISSUE THREAD

**Issue by skewty** [flathub/com.nextcloud.desktopclient.nextcloud#9]
The Launch on System Startup option does not work on the Flatpack.

Can the code detect if it is running as Flatpack and adjust the Exec= line in the .desktop created?

https://github.com/nextcloud/desktop/issues/688

**Comment by tilosp** [comment]
Moved to https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/18
